test01:
  excute_path: messages-OpenAiStyleModel
  # 需要转换的参数，指定转换形式
  converter:
    - name: messages
      type: list
      value: systemprompt,humanprompt

  components:  # 添加一个新的键来包含列表
    - name: HumanPrompt
      param:
        human_message: "{{query}}"
    - name: SystemPrompt
      param:
        system_prompt: 你是一个小助手，可以根据要求，执行任何任务。
    - name: OpenAiStyleModel
      param:
        parameter:
            model: "llama3pro"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2

embedding:
  excute_path: OpenAiStyleEmbeddings
  # 需要转换的参数，指定转换形式
  converter:
  components:  
    - name: OpenAiStyleEmbeddings
      param:
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2

add_text_vector:
  excute_path: embed_function-ChromaUpsertStore
  # 需要转换的参数，指定转换形式
  converter:
    - name: embed_function
      type: instance
      value: OpenAiStyleEmbeddings
    - name: ChromaUpsertStore
      type: instance
      value: ChromaUpsertStore
  components:  
    - name: OpenAiStyleEmbeddings
      param:
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2
    - name: ChromaUpsertStore
      param:
        embedding_func: 

query_text_vector:
  excute_path: embed_function-ChromaRetriverStore
  # 需要转换的参数，指定转换形式
  converter:
    - name: embed_function
      type: instance
      value: OpenAiStyleEmbeddings
    - name: ChromaRetriverStore
      type: instance
      value: ChromaRetriverStore
  components:  
    - name: OpenAiStyleEmbeddings
      param:
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2
    - name: ChromaRetriverStore
      param:
        embedding_func: 