chat_model:
  excute_path: messages-ModelFactory
  # 需要转换的参数，指定转换形式
  converter:
    - name: messages
      type: list
      value: systemprompt,humanprompt
    - name: ModelFactory
      type: instance
      value: ModelFactory

  components:  # 添加一个新的键来包含列表
    - name: PromtFactory
      alias: humanprompt
      param:
        component_type: human
        human_message: "{{query}}"
    - name: PromtFactory
      alias: systemprompt
      param:
        component_type: system
        system_prompt: 你是一个小助手，可以根据要求，执行任何任务。
    - name: ModelFactory
      param:
        component_type: openai
        parameter:
            model: "llama3pro"
            api_key: '123'
            base_url: http://127.0.0.1:1234
            # base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2

embedding:
  excute_path: ModelFactory
  # 需要转换的参数，指定转换形式
  converter:
    - name: ModelFactory
      type: instance
      value: ModelFactory
  components:  
    - name: ModelFactory
      param:
        component_type: openai_embedding
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2

add_text_vector:
  excute_path: embed_function-VectorFactory
  # 需要转换的参数，指定转换形式
  converter:
    - name: embed_function
      type: instance
      value: ModelFactory
    - name: VectorFactory
      type: instance
      value: VectorFactory
  components:  
    - name: ModelFactory
      param:
        component_type: openai_embedding
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2
    - name: VectorFactory
      param:
        component_type: add
        embedding_func: 

query_text_vector:
  excute_path: embed_function-VectorFactory
  # 需要转换的参数，指定转换形式
  converter:
    - name: embed_function
      type: instance
      value: ModelFactory
    - name: VectorFactory
      type: instance
      value: VectorFactory
  components:  
    - name: ModelFactory
      param:
        component_type: openai_embedding
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2
    - name: VectorFactory
      param:
        component_type: retriver
        embedding_func: 

doc_reader:
  excute_path: DocReaderFactory
  # 需要转换的参数，指定转换形式
  converter:
     - name: DocReaderFactory
       type: instance
       value: DocReaderFactory
  components:  
    - name: DocReaderFactory
      param:
        query:             

format_split:
  excute_path: DocSplitterFactory
  # 需要转换的参数，指定转换形式
  converter:
     - name: DocSplitterFactory
       type: instance
       value: DocSplitterFactory
  components:  
    - name: DocSplitterFactory
      param:
        name: DocSplitterFactory
        component_type: format


semantic_split:
  excute_path: embedding_model-DocSplitterFactory
  # 需要转换的参数，指定转换形式
  converter:
    - name: embedding_model
      type: instance
      value: ModelFactory
    - name: DocSplitterFactory
      type: instance
      value: DocSplitterFactory

  components:  
    - name: ModelFactory
      param:
        component_type: openai_embedding
        parameter:
            model: "jina-embeddings-v3"
            api_key: '123'
            base_url: http://192.168.11.11:8070
            # full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2
    - name: DocSplitterFactory
      param:
        embedding_model: 
        similarity_threshold: 70
        component_type: semantic