test01:
  excute_path: messages-OpenAiStyleModel
  # 需要转换的参数，指定转换形式
  converter:
    - name: messages
      type: list
      value: systemprompt,humanprompt

  components:  # 添加一个新的键来包含列表
    - name: HumanPrompt
      param:
        human_message: "{{query}}"
    - name: SystemPrompt
      param:
        system_prompt: 你是一个小助手，可以根据要求，执行任何任务。
    - name: OpenAiStyleModel
      param:
        parameter:
            model: "llama3pro"
            api_key: '123'
            base_url: http://127.0.0.1:1234
            full_url: http://192.168.11.11:8070/v1/chat/completions
            max_retry: 2